// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Day08.Models
{
    public partial class City
    {
        [Key]
        public int cityID { get; set; }
        [Required]
        [StringLength(50)]
        public string CityName { get; set; }
        public int cID { get; set; }

        [ForeignKey(nameof(cID))]
        [InverseProperty(nameof(Employee.Cities))]
        public virtual Employee c { get; set; }
        [ForeignKey(nameof(cID))]
        [InverseProperty(nameof(Country.Cities))]
        public virtual Country cNavigation { get; set; }
    }
}