// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Day08.Models
{
    public partial class Department
    {
        public Department()
        {
            Employees = new HashSet<Employee>();
        }

        [Key]
        public int DeptID { get; set; }
        [Required]
        [StringLength(50)]
        public string DeptName { get; set; }
        [StringLength(50)]
        [Required]
        public string DeptDesc { get; set; }

        [InverseProperty(nameof(Employee.d))]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}