// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Day08.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Cities = new HashSet<City>();
        }

        [Key]
        public int EmpID { get; set; }
        [Required]
        [StringLength(50)]
        public string EmpFname { get; set; }
        [Required]
        [StringLength(50)]
        public string EmpLname { get; set; }
        public double? EmpSalary { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? EmpHDate { get; set; }
        public int dID { get; set; }
        public int? CtyID { get; set; }

        [ForeignKey(nameof(dID))]
        [InverseProperty(nameof(Department.Employees))]
        public virtual Department d { get; set; }
        [InverseProperty(nameof(City.c))]
        public virtual ICollection<City> Cities { get; set; }
    }
}